services:
  backend:
    build:
      context: ./backend
    ports:
      - "3002:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
